apiVersion: v1
kind: Service
metadata:
  name: wepapp
  labels:
    app: webapp
    release: prometheus
spec:
  type: ClusterIP
  selector:
    app: webapp
    release: prometheus
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web